doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Article:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Blog/Post/Article/Infrastructure/DoctrineMapping'
                prefix: 'App\Blog\Post\Article\Domain\Entity'
                alias: Article
            User:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Blog/User/Infrastructure/DoctrineMapping'
                prefix: 'App\Blog\User\Domain\Entity'
                alias: User
            Category:
                type: xml
                is_bundle: false
                dir: '%kernel.project_dir%/src/Blog/Post/Category/Infrastructure/DoctrineMapping'
                prefix: 'App\Blog\Post\Category\Domain\Entity'
                alias: Category
